version: "3"

networks:
  traefik-public:
    external: true

services:

  web:
    image: suculent/syxracz
    ports:
      - 80
    networks:
      - traefik-public
    deploy:
      resources:
        reservations:
          cpus: '0.1'
          memory: 8M
        limits:
          cpus: '0.2'
          memory: 32M
      labels:
        - "traefik.http.services.syxra.loadbalancer.server.port=80"
        - "traefik.constraint-label=traefik-public"
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"

        - "traefik.http.routers.syxra-http.rule=HostRegexp:`{subdomain:.*}.syxra.cz`"
        - "traefik.http.routers.syxra-http.entrypoints=http"
        - "traefik.http.routers.syxra-http.middlewares=https-redirect"

        - "traefik.http.routers.syxra-https.rule=HostRegexp:`{subdomain:.*}.syxra.cz`"
        - "traefik.http.routers.syxra-https.entrypoints=https"
        - "traefik.http.routers.syxra-https.tls=true"
        - "traefik.http.routers.syxra-https.tls.certresolver=le"

        - "traefik.http.routers.syxra-https.tls.domains[0].main=syxra.cz"
        - "traefik.http.routers.syxra-https.tls.domains[0].sans=*.syxra.cz"

        - swarmpit.service.deployment.autoredeploy=true

