version: "3"

services:

  web:
    image: suculent/syxracz
    ports:
      - 7878
    labels:
      - "traefik.frontend.entryPoints=http"
      - "traefik.enable=true"
      - "traefik.port=7878"
      - "traefik.backend=syxra-cz"
      - "traefik.docker.network=traefik-public"
      - "traefik.frontend.rule=Host:syxra.cz"
